[features]
seeds = false
skip-lint = true

[programs.localnet]
auction = "HDW5Huoqz7Us3yiMgxAEkekHUfGvggUPLEz7WZ8uSTBY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts] 
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/bid_auction.test.ts"
client = "yarn run ts-node client/*.ts"

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
warp = true

[[test.validator.args]]
validator = ["--warp-slot"]