[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raffle = "2MPhsZEKi3aCFZmtgSw4DTFnRm26WiRdHo9U8GYHGFRR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rcrta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
